// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl03EAi6M8TDwVwj546YDnY4ltYhOWeuc',
    appId: '1:388758909563:web:e928d83308fb73e7dce8de',
    messagingSenderId: '388758909563',
    projectId: 'fluttertwitterclone-badb8',
    authDomain: 'fluttertwitterclone-badb8.firebaseapp.com',
    storageBucket: 'fluttertwitterclone-badb8.appspot.com',
    measurementId: 'G-3XQPEMQ8L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-UVUSTEPOfTWp7tIdNJA_DeykgcY0c7Q',
    appId: '1:388758909563:android:182334e8e0e8a749dce8de',
    messagingSenderId: '388758909563',
    projectId: 'fluttertwitterclone-badb8',
    storageBucket: 'fluttertwitterclone-badb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2cITYC4f9dGSoNwQ1jy_RTDJIKqht9ao',
    appId: '1:388758909563:ios:51d14709a2c8b7dbdce8de',
    messagingSenderId: '388758909563',
    projectId: 'fluttertwitterclone-badb8',
    storageBucket: 'fluttertwitterclone-badb8.appspot.com',
    androidClientId: '388758909563-vpnuf49u6n0tga75uru45iojb5gh854c.apps.googleusercontent.com',
    iosClientId: '388758909563-miv8as5ehhitia0aohommhidt1k0u3j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );
}
